# Server
server.port=${PORT:8080}

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://velorix_user:Velorix123@velorix.ayrsizi.mongodb.net/velorix?retryWrites=true&w=majority&appName=Velorix}
spring.data.mongodb.database=${MONGODB_DATABASE:velorix}

# JWT
jwt.secret=${JWT_SECRET:d33b580836e1f11910a56fd991f1258b18fce2b0e4d2f1b7bf9100c5f27b4b3f4c2198dbbfb21b4324ea0cd254c7243faa0c930fac3a55349744a0d96331d45c}
jwt.expiration.ms=86400000

# Logging
logging.level.com.velorix.backend=INFO

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:dummy@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:dummypassword}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Groq AI API
groq.api.key=${GROQ_API_KEY:dummy-groq-key}

cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}